# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171a23295f48fb0a37e223bd47ff6cbcffebad8a41f901b2c646a6b5b555982392ab078359b109bed84310fbe8e883caaee84865284973ba2a01422a1fd192af

test:
  secret_key_base: ab13df6e1d18aae3303a9ac4e492360dcb8f78da2d52de0617b3ed3ba3d7a6f52225ac52338fbadd71e40d0043476e40f3caa73f471877ee5e13648c227bd269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
